project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - sesion1.qmd

website:
  title: "Mi techo, mis kWh, mi CO₂"

lang: es

execute:
  echo: true
  warning: false
  freeze: auto   # solo re-ejecuta las celdas si el .qmd cambia
